---
- name: Get Information From ESXi
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - community.vmware
    - community.general

  tasks:
  - name: Gather some information about ESXi
    community.vmware.vmware_about_info:
      hostname: "{{ item }}"
      username: "{{ esxi_user }}"
      password: "{{ esxi_password }}"
      validate_certs: False
    delegate_to: localhost
    register: esxi_about_info
    with_items: "{{ esxi_hosts }}"

  - name: Send Report via E-mail
    community.general.mail:
      host: "{{ EMAIL_HOST }}"
      username: "{{ EMAIL_USERNAME }}"
      password: "{{ EMAIL_PASSWORD }}"
      port: "{{ EMAIL_PORT | default('465') }}"
      subject: "{{ EMAIL_SUBJECT | default('ESXi report') }}"
      body: "{{ lookup('template', 'esxi_report.j2') }}"
      from: "{{ EMAIL_FROM }}"
      to: "{{ EMAIL_TO }}"
      subtype: html
    delegate_to: localhost
    become: false
    check_mode: no
